version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_petgame
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petgame_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: petgame_api
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
